Added support in save_mesh_obj for triangle meshes
inductiva/wind-tunnel pull request #20
Opened 2024-07-23 11:53 UTC by rcvalerio

2024-07-24 11:37 UTC, hpenedones requested changes
Thanks @rcvalerio , left some small suggestions

2024-07-24 11:37 UTC, hpenedones commented on windtunnel/pre_processing.py
> +    if faces.shape[0] % 3 == 0:
Please apply the DRY principle here, use the if just o detect the shape_vertices (either 3 or 4) but then the call to Trimesh is the same, passing the variable in the reshape.

2024-07-24 11:37 UTC, hpenedones commented on windtunnel/windtunnel.py
> +        if isinstance(mesh, pv.MultiBlock):
a bit unclear what this is doing... is it related to the description of this pull request (save triangle meshes) or something else? Perhaps encapsulating this under a function and giving it a clear name would help...

2024-07-24 11:37 UTC, hpenedones commented on windtunnel/display.py
> +    def add_force_coefficients(self, coefficients: dict):
Seems a bit unrelated with the title of the Pull request...  Should the title and description be updated (or ideally, add this in separate pull request)?

2024-08-01 08:55 UTC, rcvalerio commented
[14de76c](https://github.com/inductiva/wind-tunnel/pull/20/commits/14de76c4d23781eb8c6b71cf690e02bd7479877a) was moved to #20

2024-08-01 09:04 UTC, rcvalerio commented
[d438616](https://github.com/inductiva/wind-tunnel/pull/20/commits/d4386161d510399aa7df64db330d4e8f2ed2b6e1) was moved to #22

2024-08-01 09:19 UTC, rcvalerio commented
[9682dfc](https://github.com/inductiva/wind-tunnel/pull/20/commits/9682dfcc4a8a9c923f7da2e4b1aa98133c42425b) was moved to #23

2024-08-01 09:20 UTC, rcvalerio commented
[83b2a0e](https://github.com/inductiva/wind-tunnel/pull/20/commits/83b2a0ebf9beff84c04265c1b2628d9f98ddb339) was moved to #24

2024-08-01 09:22 UTC, rcvalerio commented
[33095e3](https://github.com/inductiva/wind-tunnel/pull/20/commits/33095e3bfa04d23b9432fd2c5485196955d4bc76) was moved to #25

2024-08-01 09:23 UTC, rcvalerio commented
All the unrelated commits where to moved to isolated pull requests, hence this pull request is no longer needed.

2024-08-01 09:23 UTC, closed without merging